action = { 0: {'funcao' : ['shift', 2]},
            1: {'&' : ['STOP']},
            2: {'variavel' : ['shift', 3]},
            3: {'AP' : ['shift', 4]},
            4: {'int': ['shift', 7], 'string': ['shift', 8], 'FP': ['shift', 9]},
            5: {'FP' : ['shift', 9]},
            6: {'variavel': ['shift', 10]},
            7: {'variavel': ['reduce', 1, '<TIPO>']},
            8: {'variavel': ['reduce', 1, '<TIPO>']},
            9: {'AC': ['shift', 11]},
            10: {'FP': ['reduce', 0, '<PARANS>'], 'VIRGULA': ['shift', 13]},
            11: {'if': ['shift', 19], 'FC': ['shift', 25], 'variavel': ['shift', 22], 'cont': ['shift', 23], 'PRINT':['shift', 20]},
            12: {'FP': ['reduce', 3, '<PARAN>']},
            13: {'int': ['shift', 7], 'string': ['shift', 8]},
            14: {'FC': ['shift', 27]},
            15: {'if': ['shift', 19], 'FC': ['shift', 47], 'variavel': ['shift', 22], 'cont': ['shift', 23], 'PRINT':['shift', 20]},
            17: {'FC': ['reduce', 1, '<ESCOPO>'], 'if' : ['reduce', 1, '<ESCOPO>'], 'PRINT' : ['reduce', 1, '<ESCOPO>'], 'variavel': ['reduce', 1, '<ESCOPO>'], 'cont': ['reduce', 1, '<ESCOPO>']},
            19: {'AP': ['shift', 27]},
            20: {'AP': ['shift', 28]},
            21: {'igual': ['shift', 29]},
            22: {'igual': ['reduce', 1, '<VAR>'], 'FP': ['reduce', 1, '<VAR>'], 'PV': ['reduce', 1, '<VAR>'], 'menor' : ['reduce', 1, '<VAR>'], 'maior': ['reduce',1, '<VAR>']},
            23: {'igual': ['reduce', 1, '<VAR>'], 'FP': ['reduce', 1, '<VAR>'], 'PV': ['reduce', 1, '<VAR>'], 'menor' : ['reduce', 1, '<VAR>'], 'maior': ['reduce',1, '<VAR>']},
            24: {'AP': ['shift', 28]},
            25: {'&' : ['reduce', 7,'<FUNCAO>']},
            26: {'AP': ['shift', 28]},
            27: {'variavel': ['shift', 22], 'cont': ['shift', 23]},
            28: {'variavel': ['shift', 22], 'cont': ['shift', 23]},
            29: {'variavel': ['shift', 22], 'cont': ['shift', 23]},
            30: {'FP': ['shift', 34]},
            31: {'maior': ['shift', 36], 'menor': ['shift', 37]},
            32: {'FP': ['shift', 38]},
            33: {'PV': ['shift', 39]},
            34: {'AC': ['shift', 40]},
            35: {'variavel': ['shift', 23], 'cont': ['shift', 23]},
            36: {'variavel': ['reduce', 1, '<SCOND>'], 'cont': ['reduce', 1, '<SCOND>']},
            37: {'variavel': ['reduce', 1, '<SCOND>'], 'cont': ['reduce', 1, '<SCOND>']},
            38: {'PV': ['shift', 42]},
            39: {'FC': ['reduce', 4, '<ATRIB>'], 'if' : ['reduce', 4, '<ATRIB>'], 'PRINT' : ['reduce', 4, '<ATRIB>'], 'variavel': ['reduce', 4, '<ATRIB>'], 'cont': ['reduce', 4, '<ATRIB>']},
            40: {'FC': ['shift', 44], 'variavel': ['shift', 23], 'cont': ['shift', 23], 'if' : ['shift',19], 'PRINT' : ['shift',20]},
            41: {'FP': ['reduce', 3, '<COND>']},
            42:  {'FC': ['reduce', 5, '<PRINT>'], 'if' : ['reduce', 5, '<PRINT>'], 'PRINT' : ['reduce', 5, '<PRINT>'], 'variavel': ['reduce', 5, '<PRINT>'], 'cont': ['reduce', 5, '<PRINT>']},
            43: {'FC': ['shift', 44]},
            44: {'FC': ['reduce', 7, '<IF>'], 'if' : ['reduce', 7, '<IF>'], 'PRINT' : ['reduce', 7, '<IF>'], 'variavel': ['reduce', 7, '<IF>'], 'cont': ['reduce', 7, '<IF>']},
            47: {'&' : ['reduce', 8,'<FUNCAO>']},
}