action = { 0: {'funcao' : ['shift', 2]},
            2: {'variavel' : ['shift', 3]},
            3: {'AP' : ['shift', 4]},
            4: {'int': ['shift', 7], 'string': ['shift', 8], 'FP': ['reduce', [4, '<PARAN>']]},
            5: {'FP' : ['shift', 9]},
            6: {'variavel': ['shift', 10]},
            7: {'variavel': ['reduce', 6]},
            8: {'variavel': ['reduce', 6]},
            9: {'AC': ['shift', 11]},
            10: {'FP': ['reduce', 5], 'VIRGULA': ['shift', 13]},
            11: {'if': ['shift', 19], 'FC': ['shift', 25], 'variavel': ['shift', 22], 'cont': ['shift', 23], 'PRINT':['shift', 20]},
            12: {'FP': ['reduce', 5]},
            13: {'int': ['shift', 7], 'string': ['shift', 8]},
            14: {'FC': ['shift', 27]},
            15: {'if': ['shift', 19], 'FC': ['shift', 25], 'variavel': ['shift', 22], 'cont': ['shift', 23], 'PRINT':['shift', 20]},
            19: {'AP': ['shift', 27]},
            20: {'AP': ['shift', 28]},
            21: {'igual': ['shift', 29]},
            22: {'igual': ['reduce', 21], 'FP': ['reduce', 32], 'PV': ['reduce', 33]},
            23: {'igual': ['reduce', 21], 'FP': ['reduce', 32], 'PV': ['reduce', 33]},
            24: {'AP': ['shift', 28]},
            25: {'&' : ['STOP']},
            26: {'AP': ['shift', 28]},
            27: {'variavel': ['shift', 45], 'cont': ['shift', 46]},
            28: {'variavel': ['shift', 22], 'cont': ['shift', 23]},
            29: {'variavel': ['shift', 22], 'cont': ['shift', 23]},
            30: {'FP': ['shift', 34]},
            31: {'maior': ['shift', 36], 'menor': ['shift', 37]},
            32: {'FP': ['shift', 38]},
            33: {'PV': ['shift', 39]},
            34: {'AC': ['shift', 40]},
            35: {'variavel': ['shift', 45], 'cont': ['shift', 46]},
            36: {'variavel': ['reduce', 35], 'cont': ['reduce', 35]},
            37: {'variavel': ['reduce', 35], 'cont': ['reduce', 35]},
            38: {'PV': ['shift', 42]},
            39: {'FC': ['reduce', 15]},
            40: {'FC': ['reduce', 15], 'variavel': ['shift', 45], 'cont': ['shift', 46]},
            42: {'FC': ['shift', 25], 'if' : ['shift',19], 'print' : ['shift',20], 'variavel': ['shift', 45], 'cont': ['shift', 46]},

            45: {'menor' : ['reduce', 31], 'maior': ['reduce', 31], 'FP' : ['reduce', 30], 'igual': ['reduce', 21]},
            46: {'menor' : ['reduce', 31], 'maior': ['reduce', 31], 'FP' : ['reduce', 30], 'igual': ['reduce', 21]},
}